### PR TITLE
[Feature Request]: Reference actions by commit SHA

### PR DESCRIPTION
**Pull request by gabibguti**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build was run locally and without warnings or errors
- [ ] All previous and new tests pass

## Pull request type

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming, typo fix)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
Referencing actions by major tag (e.g. `v3`)

Related Issue URL: https://github.com/tukaani-project/xz/issues/65

## What is the new behavior?

Referencing actions by commit SHA (e.g. `8ade135a41bc03ea155e62e844d188df1ea18608`)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JiaT75** [comment]
Thanks for remaking the PR!

Everything looks great except can you tweak your commit messages slightly? If you could prepend "CI:" before the first line of your commit message ("Bump and ref actions...") that would be great. We like to do that to help search/filter commits by category. Also, in the first commit can you mention the reason why this change is needed? Something like the text from #65 could be enough:

"Referencing actions by commit SHA in GitHub workflows guarantees you are using an immutable version. Actions referenced by tags and branches are more vulnerable to attacks, such as the tag being moved to a malicious commit or a malicious commit being pushed to the branch."

Or if you want to reword it at all.

**Comment by gabibguti** [comment]
Yes sure! Will do!

**Comment by gabibguti** [comment]
See if it looks better now

**Comment by JiaT75** [comment]
It looks great! Thanks

**Comment by gabibguti** [comment]
Thanks for the advice! I will follow that for future commit messages!

**Pull request merged**
