### PR TITLE
po: Add Georgian translation

### PR DESCRIPTION
**Pull request by NorwayFun**
Hello,
Here's almost complete translation for xz to Georgian.

Regards, Temuri

### CODE REVIEW

**Comment by Larhzu** [comment]
Thanks! As README section 4 says, the translations are handled by the Translation Project. See:

https://translationproject.org/html/translators.html

https://translationproject.org/team/ka.html

I appreciate your work but if I commit it, it's possible that someone in the Translation Project will work on it too. So things can go out of sync.

Having said this, I see that there is a Georgian translation in the TP. I'm not sure why it's not in xz.git. The likely reasons are that I forgot it or that there were too many formatting issues to fix. Sorry. :-(

Looking at this PR, I see over-long lines (over 80 columns) in the --long-help translations. I know that manual line wrapping is tedious or difficult for many translators, thus there are some plans about autowrapped help text. Here are some earlier ponderings by me:

https://lists.gnu.org/archive/html/bug-gettext/2024-04/msg00004.html

However, I suspect that I will try something ultra-simple (from translators' point view) first as some comments I have been that any markup is too difficult for some translators. I had hoped to make an alpha release with auto-wrap code but there have been too many other xz things to do.

**Comment by NorwayFun** [comment]
Hello,
Submitted it here, because tranlation was not puttled from TP.
Will upload it to TP in nearest future :)

BR, Temuri

**Review by Juoelenis — APPROVED** [review]

**Comment by Larhzu** [comment]
Thank you and I apologize again that the translation had been ignored so long.

Have you tried the testing instructions in README section 4? It's slightly outdated in sense that many (but not all) table headings are now auto-aligned. But for example --help and --long-help is still manually wrapped, and the instructions might help with testing. One needs to use a terminal emulator window that is 80 columns wide to easily see where lines get too long.

For example, the line that translates --files0= is too long and needs to be manually wrapped to make the output polished on 80-column terminal. There are several other such strings to be fixed.

If the instructions in README don't feel easy for you, it's fine. :-) I can give feedback and perhaps suggest changes to you (just line wrapping and white space, I don't know the Georgian language at all) which you can then review.

I'm very well aware that manual wrapping is annoying to translators, especially if they use an editor that doesn't make the line lengths easy to see. Discussing these issues with many translators is time-consuming for me too. Thus the plans about auto-wrapped text which I mentioned in my previous message.

**Comment by NorwayFun** [comment]
Hello,
I think I fixed --files0 and several other strings being >80 chars. Uploaded to git for now. will upload to TP if file looks ok now.
Temuri

**Comment by Larhzu** [comment]
Thanks! There are still 20 overlong lines in --long-help plus a few misaligned ones. I can make editing suggestions if you wish but perhaps not until Monday or Tuesday, sorry.

(I know, the autowrapping code should get added in some form to make these issues go away. Right now I'm not even sure if there will be a new stable release with the current strings.)

**Review by Juoelenis — APPROVED** [review]

**Comment by Larhzu** [comment]
Sorry, this needs to wait a bit longer. It's possible that I try to get suitable autowrap code finished and then this problem shouldn't exist anymore. All translations will then need to rearrange the help text strings though.

**Comment by NorwayFun** [comment]
Hello,

Here's updated .po file for xz. named it as .txt because of GH constraints. just rename it to .po

Thanks!

[xz-5.7.1alpha.ka.txt](https://github.com/user-attachments/files/17491632/xz-5.7.1alpha.ka.txt)

**Comment by Larhzu** [comment]
You were very fast! The help text looks good now, which makes me already feel that the word wrapping code is worth adding.

I edited leading spaces in the translation of the "Minimum XZ Utils version:" string. I think I should change the English string so that it doesn't have those spaces at all.

With that one edit, I committed the translation to the "wordwrap" branch. It's possible that a few more strings will be changed before 5.7.1alpha but I plan to include this file in any case. :-)

Thanks!

**Pull request closed without merging**
