### PR TITLE
[Feature Request]: Reference actions by commit SHA

### PR DESCRIPTION
**Pull request by gabibguti**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build was run locally and without warnings or errors
- [ ] All previous and new tests pass

## Pull request type

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming, typo fix)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Referencing actions by major tag (e.g. `v3`)

Related Issue URL: https://github.com/tukaani-project/xz/issues/65

## What is the new behavior?

Referencing actions by commit SHA (e.g. `8ade135a41bc03ea155e62e844d188df1ea18608`)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gabibguti** [comment]
## Other information
`windows-ci` is failing in my fork. I tested it on the [last commit it was working](https://github.com/tukaani-project/xz/commit/bf65f25ac8fa8b6686459c004759d8b77ba17502) without changes and it failed too, maybe it needs some data only the original repository has?

**Comment by gabibguti** [comment]
An idea to fix `windows-ci`: I can add a trigger to run `on: pull_request` in my fork and test if the workflow is working on this PR.

**Comment by gabibguti** [comment]
I think the failure is not related to the PR changes, can you confirm by running the workflow on the repository?

**Comment by gabibguti** [comment]
Closing this PR to make more tests locally.

**Comment by JiaT75** [comment]
@gabibguti It looks like Windows CI is broken on the master branch, so thanks for letting us know. I have it set it up to only run manually because it runs much slower than Ubuntu and Mac OS runners. I suppose I should manually run it more often.

We have been doing a few Windows related changes for xz recently so thats likely what broke it. I will investigate the issue and let you know when  it is fixed.

**Comment by gabibguti** [comment]
Ok, thanks for the confirmation, Jia!

**Pull request closed without merging**
